baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "ru"
title = "itout.one"
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[sitemap]
  changeFreq = 'monthly'
  filename = 'sitemap.xml'
  priority = -1

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = "G-G22DNLHXE0"
  favicon = "favicon_32х32.svg"

  [params.homepage]
    show_contact_box = true      # show / hide the contaxt box on the homepage
    show_services_button = true # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo_mobile.svg"
    mobile_height = "60px"
    desktop = "images/logo/logo.svg"
    desktop_height = "40px"
    alt = "IT-аутсорсинг - itout.one"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#3664AD"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = ""
    meta_twitter_creator = ""
    meta_og_image = ""

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '<a class="zerostatic" href="https://www.itout.one/">www.itout.one</a> © 2024<br />Email: <a class="zerostatic" href="mailto:hello@itout.one">hello@itout.one</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Услуги"
    url = "/services/"
    weight = 2

  [[menu.main]]
    name = "О нас"
    url = "/about/"
    weight = 3

  [[menu.main]]
    name = "Контакты"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Услуги"
    url = "/services/"
    weight = 2

  [[menu.footer]]
    name = "О нас"
    url = "/about/"
    weight = 3

  [[menu.footer]]
    name = "Вакансии"
    url = "/job/"
    weight = 4

  [[menu.footer]]
    name = "Сайт"
    url = "/website/"
    weight = 5

  [[menu.footer]]
    name = "Контакты"
    url = "/contact/"
    weight = 6